id: 'tt07' 
name: 'Tiny Tapeout 7'
end_date: '2024-06-01'
project_dir: 'projects'
openframe: true

datasheet_config:

  artwork:
    - {id: TT_POCA_01_A, rotate: 90deg}
    - {id: TT_POCA_01_B, rotate: 90deg}
    - {id: TT_POCA_01_C, rotate: 90deg}
    - {id: TT_POCA_01_D, rotate: 90deg}
    - {id: TT_POCA_01_E, rotate: 90deg}
    - {id: TT_POCA_01_F, rotate: 90deg}
    - {id: TT_POCA_01_G, rotate: 90deg}
    - {id: TT_POCA_01_H, rotate: -90deg}
    - {id: TT_POCA_01_I, rotate: 90deg}

  disabled:
    - tt_um_pwm_elded
    - tt_um_wokwi_399169514887574529
    - tt_um_afasolino
    - tt_um_neural_network
    - tt_um_eater_8bit
    - tt_um_calonso88_74181
    - tt_um_dvxf_dj8v_dac
    - tt_um_maheredia
    - tt_um_dusterthefirst_project

  include:
    - docs/chip_map.typ
    - docs/funding.typ